// Course, Statistic, and Feature data structures

export const statistics = [
    { id: 1, value: "10+", label: "Years of Excellence" },
    { id: 2, value: "5000+", label: "Students Trained" },
    { id: 3, value: "50+", label: "Expert Trainers" },
    { id: 4, value: "95%", label: "Placement Record" },
];

export const features = [
    {
        id: 1,
        icon: "Award",
        title: "Certified Training",
        description: "Get industry-recognized certifications upon course completion",
    },
    {
        id: 2,
        icon: "Users",
        title: "Expert Trainers",
        description: "Learn from experienced professionals with real-world expertise",
    },
    {
        id: 3,
        icon: "Clock",
        title: "Flexible Timings",
        description: "Choose from weekday, weekend, and fast-track batches",
    },
    {
        id: 4,
        icon: "Briefcase",
        title: "100% Job Support",
        description: "Comprehensive placement assistance and career guidance",
    },
];

export const courses = [
    // Popular Courses
    {
        id: 1,
        title: "Full Stack Java",
        description: "Master Java programming from basics to advanced concepts. Learn object-oriented programming, data structures, and build real-world applications with industry best practices.",
        category: "Popular",
        rating: 4.8,
        reviews: 245,
        price: 15000,
        duration: "3 Months",
        level: "Beginner to Advanced",
        badge: "Bestseller",
    },
    {
        id: 2,
        title: "Full Stack Python",
        description: "Learn Python programming for web development, data analysis, and automation. Master Django, Flask, and popular Python libraries to build powerful applications.",
        category: "Popular",
        rating: 4.9,
        reviews: 312,
        price: 18000,
        duration: "3 Months",
        level: "All Levels",
        badge: "Bestseller",
    },
    {
        id: 3,
        title: "Python + Sql + Prob & Stat + DS(Machine Learning) + AI(Deep Learning) Power bi",
        description: "Learn Python, SQL, ML, AI, and Power BI in one complete program designed to make you a job-ready Data Science professional. Gain strong analytical, modeling, and visualization skills for real business applications.",
        category: "Popular",
        rating: 4.7,
        reviews: 198,
        price: 22000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 4,
        title: "Data Science",
        description: "Transform your career with comprehensive data science training. Master Python, R, machine learning, statistics, and data visualization to become a data scientist.",
        category: "Popular",
        rating: 4.9,
        reviews: 287,
        price: 35000,
        duration: "6 Months",
        level: "Advanced",
        badge: "Bestseller",
    },
    {
        id: 5,
        title: "Python +SQL+ Probability with statistics + Adv excel +Power bi",
        description: "Master data handling from end to end with Python, SQL, Advanced Excel, and Power BI. Build strong statistical foundations and create complete business-ready data solutions.",
        category: "Popular",
        rating: 4.8,
        reviews: 223,
        price: 40000,
        duration: "6 Months",
        level: "All Levels",
    },
    {
        id: 6,
        title: "Advance Excel",
        description: "Master formulas, dashboards, pivot tables, automation, and data analysis techniques in Excel. Upgrade your professional skills to handle large datasets and create powerful business insights.",
        category: "Popular",
        rating: 4.7,
        reviews: 176,
        price: 16000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 101,
        title: "Python + SQL + Adv. Excel + Power BI",
        description: "Gain strong data analytics skills with Python programming, SQL querying, Advanced Excel tools, and Power BI dashboards. Learn to manage, analyze, and visualize data for real-world business applications.",
        category: "Popular",
        rating: 4.8,
        reviews: 198,
        price: 14000,
        duration: "2 Months",
        level: "All Levels",
    },
    // Trending Courses
    {
        id: 7,
        title: "Full Stack Java",
        description: "Become a job-ready Java Full Stack Developer by mastering Core Java, JDBC, Spring Boot, Hibernate, and modern frontend technologies. Build real-world applications with end-to-end development skills.",
        category: "Trending",
        rating: 4.8,
        reviews: 189,
        price: 28000,
        duration: "4 Months",
        level: "Intermediate",
        badge: "Trending",
    },
    {
        id: 8,
        title: "Full Stack Python",
        description: "Learn Python, Django/Flask, SQL, and frontend technologies to become a complete Full Stack Python Developer. Build scalable web applications from backend logic to UI design.",
        category: "Trending",
        rating: 4.7,
        reviews: 165,
        price: 25000,
        duration: "3 Months",
        level: "Advanced",
        badge: "Trending",
    },
    {
        id: 9,
        title: "Software Testing",
        description: "Master Manual and Automation Testing with Selenium, TestNG, JUnit, API Testing, and QA processes. Gain the skills to ensure software quality and perform real-world test execution.",
        category: "Trending",
        rating: 4.9,
        reviews: 234,
        price: 38000,
        duration: "5 Months",
        level: "Advanced",
    },
    {
        id: 104,
        title: "UI/UX",
        description: "Learn UI/UX fundamentals, wireframing, prototyping, and design tools like Figma & Adobe XD. Build user-friendly, visually appealing digital experiences with real project practice.",
        category: "Trending",
        rating: 4.9,
        reviews: 201,
        price: 42000,
        duration: "6 Months",
        level: "Advanced",
        badge: "Bestseller",
    },
    {
        id: 105,
        title: "Web Full Stack",
        description: "Become a Full Stack Web Developer with expertise in HTML, CSS, JavaScript, React, Node.js, Express, and MongoDB. Learn to build complete, modern web applications from frontend to backend.",
        category: "Trending",
        rating: 4.6,
        reviews: 143,
        price: 32000,
        duration: "4 Months",
        level: "Intermediate",
        badge: "Trending",
    },
    {
        id: 106,
        title: "Web Development",
        description: "Learn the core of web development with HTML, CSS, JavaScript, and responsive design principles. Start building modern, interactive websites and prepare for advanced full-stack learning.",
        category: "Trending",
        rating: 4.8,
        reviews: 178,
        price: 26000,
        duration: "3 Months",
        level: "Intermediate",
    },
   

    // Networking Courses
    {
        id: 10,
        title: "CCNA + Linux + AWS",
        description: "Master networking with CCNA, strengthen server skills with Linux, and learn cloud deployment using AWS. Become a versatile IT professional capable of handling networks, servers, and cloud infrastructure.",
        category: "Networking",
        rating: 4.6,
        reviews: 142,
        price: 18000,
        duration: "2 Months",
        level: "Beginner",
    },
    {
        id: 11,
        title: "CCNA",
        description: "Learn core networking concepts including routing, switching, IP addressing, and network security. Prepare for the CCNA certification with hands-on labs and real-world networking scenarios.",
        category: "Networking",
        rating: 4.7,
        reviews: 98,
        price: 25000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 12,
        title: "CCNA + Linux + CEH",
        description: "Build strong networking and Linux administration skills, then learn ethical hacking tools and techniques with CEH. Become job-ready in IT infrastructure and cybersecurity operations.",
        category: "Networking",
        rating: 4.5,
        reviews: 87,
        price: 22000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 109,
        title: "Cyber Security Analyst Program",
        description: "Learn network security, ethical hacking, threat detection, SOC tools, and incident response. Get trained to monitor, analyze, and protect organizational systems against cyber attacks.",
        category: "Networking",
        rating: 4.6,
        reviews: 134,
        price: 16000,
        duration: "2 Months",
        level: "Beginner",
    },
    {
        id: 110,
        title: "CCNA + Linux + AWS + DevOps",
        description: "Gain expertise in networking, Linux administration, AWS cloud services, and DevOps automation tools. Become a complete infrastructure engineer capable of managing and deploying scalable systems.",
        category: "Networking",
        rating: 4.5,
        reviews: 89,
        price: 19000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 111,
        title: "Salesforce ADM + DEV (PD-1 + LWC)",
        description: "Master Salesforce Administration and Development with Apex, Visualforce, and Lightning Web Components. Build CRM applications and prepare for ADM, PD-1, and LWC certifications.",
        category: "Networking",
        rating: 4.7,
        reviews: 156,
        price: 21000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 112,
        title: "DevOps",
        description: "Learn CI/CD pipelines, Git, Docker, Kubernetes, Jenkins, and Infrastructure as Code. Become proficient in automating software development and deployment processes.",
        category: "Networking",
        rating: 4.7,
        reviews: 156,
        price: 21000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 111,
        title: "Cloud Computing",
        description: "Understand cloud architecture, virtualization, storage, networking, and deployment models across leading cloud platforms. Gain skills to build, scale, and manage applications in the cloud.",
        category: "Networking",
        rating: 4.7,
        reviews: 156,
        price: 21000,
        duration: "3 Months",
        level: "Intermediate",
    },

    // Software Courses
    {
        id: 13,
        title: "AP MM S4 HANA",
        description: "Master Material Management processes using SAP S/4 HANA’s advanced inventory, procurement, and logistics tools. Gain hands-on experience to manage end-to-end supply chain operations in modern enterprises.",
        category: "SAP",
        rating: 4.6,
        reviews: 156,
        price: 16000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 14,
        title: "SAP FICO S4 HANA",
        description: "Learn Financial Accounting and Controlling on the latest SAP S/4 HANA platform. Develop skills to manage financial statements, cost control, and real-time financial reporting for global businesses.",
        category: "SAP",
        rating: 4.7,
        reviews: 189,
        price: 18000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 15,
        title: "SAP FICO",
        description: "Understand core Financial Accounting and Controlling concepts in SAP ERP. Learn to handle financial transactions, budgeting, cost analysis, and business reporting with practical case studies.",
        category: "SAP",
        rating: 4.8,
        reviews: 203,
        price: 15000,
        duration: "3 Months",
        level: "Beginner",
    },
    {
        id: 112,
        title: "SAP MM",
        description: "Gain expertise in procurement, vendor management, inventory control, and material planning within SAP ERP. Learn to manage supply chain operations using industry-standard SAP MM tools.",
        category: "SAP",
        rating: 4.6,
        reviews: 145,
        price: 15000,
        duration: "2 Months",
        level: "Intermediate",
    },
   
    // Data Science Courses
    {
        id: 16,
        title: "Softskill",
        description: "Develop essential communication, teamwork, leadership, and problem-solving abilities. Build confidence and improve your professional presence for workplace success.",
        category: "Data Science",
        rating: 4.8,
        reviews: 267,
        price: 32000,
        duration: "4 Months",
        level: "All Levels",
    },
    {
        id: 17,
        title: "Softskill & Personality Development",
        description: "Enhance your communication, behavior, and confidence while improving your overall personality. Learn workplace etiquette, public speaking, and interpersonal skills for career growth.",
        category: "Data Science",
        rating: 4.7,
        reviews: 145,
        price: 30000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 18,
        title: "German A1 & A2",
        description: "Learn German from beginner to elementary levels with speaking, reading, writing, and listening practice. Build strong grammar basics and everyday conversation skills for study, travel, or work in Germany.",
        category: "Data Science",
        rating: 4.6,
        reviews: 198,
        price: 14000,
        duration: "1 Month",
        level: "Beginner",
    },
    {
        id: 117,
        title: "German A1",
        description: "Start your German language journey with fundamental vocabulary, grammar, and simple conversations. Learn to introduce yourself, ask questions, and communicate basic everyday needs.",
        category: "Data Science",
        rating: 4.7,
        reviews: 176,
        price: 15000,
        duration: "1.5 Months",
        level: "Beginner",
    },
    {
        id: 118,
        title: "HR Generalist",
        description: "Master core HR functions including recruitment, payroll, compliance, onboarding, performance management, and HR documentation. Become job-ready with practical training in real HR processes.",
        category: "Data Science",
        rating: 4.6,
        reviews: 134,
        price: 18000,
        duration: "2 Months",
        level: "Intermediate",
    },
   

];

export const getCoursesByCategory = (category) => {
    return courses.filter((course) => course.category === category);
};

export const categories = [
    "Popular",
    "Trending",
    "Networking",
    "Data Science",
    "SAP",  
];
